# filebin.netのBinID
bin-id: "mc-world"

# アーカイブファイル名のプレフィックス
archive-prefix: "world-"

# ログイン時のアナウンスメッセージ
login-message: |-
  ----------------------------------------------
  
    ようこそ！バニラサーバーへ！
  
    遊んだあとは、§e/download§r と打つことで
    ワールドをダウンロードできますよ！
  
  ----------------------------------------------
